### ISSUE TITLE
Retrieve Licensing info for ILAMB-data

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/ILAMB-workflow#11]
The ILAMB-data datasets do not have licensing information.
We need that on NCI

**Comment by rbeucher** [comment]
I think a good starting point is the ILAMB paper
https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2018MS001354

See Tables

**Comment by rbeucher** [comment]
@JamesWilmot

**Comment by JamesWilmot** [comment]
| Name | Paper | Other notes | File path | License |
| -------- | -------- | ------------- | ------------- | ------------ |
| AVH15C1 | https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.ncdc:C01559/html# https://registry.opendata.aws/noaa-cdr-terrestrial/   |     | ```DATA/lai/AVH15C1/lai.nc``` |  Open data  |
| AVHRR |  https://ieeexplore.ieee.org/document/649788   |  This product was derived from half monthly AVHRR BU leaf area index from Boston University.   | ```DATA/lai/AVHRR/lai_0.5x0.5.nc``` | 
| CERESed4.1 | https://doi.org/10.1175/JCLI-D-17-0208.1 |  2019-06-25: downloaded source from https://ceres.larc.nasa.gov/products-info.php?product=EBAF;\n2019-08-13   | ```DATA/rlds/CERESed4.1/rlds.nc``` |
| CLASS |  doi:10.1175/JCLI-D-19-0036.1  |  https://zenodo.org/record/4922154 Already available in NCI at ```/g/data/ks32/ARCCSS_Data/CLASS/v1-1/``` but in a different format  | ```DATA/mrro/CLASS/mrro.nc``` |
| CMAPv1904 |  https://journals.ametsoc.org/view/journals/bams/78/11/1520-0477_1997_078_2539_gpayma_2_0_co_2.xml  | https://psl.noaa.gov/data/gridded/data.cmap.html#detail;\n2019-07-01   | ```DATA/pr/CMAPv1904/pr.nc``` |
| CRU4.02 |  https://doi.org/10.1002/joc.3711  |    https://crudata.uea.ac.uk/cru/data/hrg/cru_ts_4.02/;\n2019-05-06  | ```DATA/tasmax/CRU4.02/tasmax.nc``` |
| CanSISE |    |  https://nsidc.org/data/nsidc-0668/versions/2    | ```DATA/swe/CanSISE/swe.nc``` |
| DOLCE |  http://dx.doi.org/10.4225/41/58980b55b0495  |   Hobeichi, Sanaa, 2017: Derived Optimal Linear Combination Evapotranspiration v1.0 . NCI National Research Data Collection , doi:10.4225/41/58980b55b0495 Hobeichi, S., Abramowitz, G., Evans J. and A. Ukkola. Derived Optimal Linear Combination Evapotranspiration (DOLCE): a global gridded synthesis ET estimate (in prep.)   https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f3535_5828_5475_8492  | ```DATA/evspsbl/DOLCE/DOLCE.nc``` |
| Dai |    |   This product is generated from yearly GRDC_Aiguo observations https://rda.ucar.edu/datasets/ds551.0/  | ```DATA/mrro/Dai/runoff.nc``` |
| Davies-Barnard |  https://doi.org/10.1029/2019GB006387   |   A comprehensive global meta analysis of field measurements   | ```DATA/fBNF/DaviesBarnard/fBNF_0.5x0.5.nc``` |
| ERA5 |  https://doi.org/10.1002/joc.3711  |  Derivative of CRU dataset   | ```DATA/rhums/ERA5/rhums.nc``` |
| ESACCI |  http://dx.doi.org/10.5285/5f331c418e9f4935b8eb1b836f8a91b8  |  https://dap.ceda.ac.uk/neodc/esacci/esacci_terms_and_conditions.txt   |  ```DATA/biomass/ESACCI/biomass.nc```    | The CCI datasets held on the CCI Open Data Portal may be used by any user for any purpose, with terms & conditions ie must cite |
| FLUXCOM |  https://doi.org/10.5194/bg-13-4291-2016  |   Data generated by Artificial Neural Networks and forced with CRUNCEPv6 meteorological data and MODIS (RS+METEO)  | ```DATA/reco/FLUXCOM/reco.nc``` |
| FLUXNET2015 |  https://doi.org/10.1111/j.1365-2486.2009.02041.x  |   FluxNet Tower eddy covariance measurements (Tier 1)  | ```DATA/gpp/FLUXNET2015/gpp.nc``` |
| GCP | doi:10.5194/essd-8-605-2016   |   https://www.globalcarbonproject.org/carbonbudget/22/data.htm  | ```DATA/nbp/GCP/nbp_1959-2016.nc``` | The data and model output provided on this site are freely available and were furnished by individual scientists who encourage their use.  | 
| GEWEX.SRB |    |  This product was derived from NASA GEWEX SRB radiation dataset.   | ```DATA/rlds/GEWEX.SRB/rlds_0.5x0.5.nc``` |
| GFED4.1S |  https://doi.org/10.1002/jgrg.20042  |   https://www.geo.vu.nl/~gwerf/GFED/GFED4/Readme.pdf  | ```DATA/burntArea/GFED4.1S/burntArea.nc``` |
| GLEAMv3.3a |  https://doi.org/10.5194/hess-15-453-2011  |   https://www.gleam.eu/  | ```DATA/evspsbl/GLEAMv3.3a/et.nc``` | The datasets described in the above section are freely available. |
| GPCCv2018 |  http://dx.doi.org/10.3390/atmos8030052  |   https://www.dwd.de/EN/ourservices/gpcc/gpcc.html  | ```DATA/pr/GPCCv2018/pr.nc``` | The GPCC provides unrestricted access to its gridded monthly and daily precipitation data sets for climate monitoring purposes and related research. All users are requested to refer to the GPCC and the product specific DOI (Digital Object Identifier) reference as provided with the products.  |
| GPCPv2.3 | https://doi.org/10.1175/1525-7541(2003)004<1147:TVGPCP>2.0.CO;2   | http://www.esrl.noaa.gov/psd/data/gridded/data.gpcp.html    | ```DATA/pr/GPCPv2.3/pr.nc``` | Usage Restrictions: None | 
| GRACE |    |    This product is generated from monthly 1 degree GRACE Tellus CSR observations https://grace.jpl.nasa.gov/data/get-data/monthly-mass-grids-land/ | ```DATA/twsa/GRACE/twsa_0.5x0.5.nc``` |
| GlobalCarbon |   https://doi.org/10.1073/pnas.1019576108  |  A combination of data in situ inventory plots and satellite light detection and ranging (Lidar) samples"   | ```DATA/biomass/GLOBAL.CARBON/biomass_0.5x0.5.nc``` |
| HWSD |    |   This product was derived from Harmonized World Soil Database (HWSD) v1.2 dataset. https://www.fao.org/soils-portal/data-hub/soil-maps-and-databases/harmonized-world-soil-database-v12/en/  https://www.fao.org/3/aq361e/aq361e.pdf  |  ```DATA/cSoil/HWSD/soilc_0.5x0.5.nc``` |
| Hoffman |   https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2013JG002381 |     | ```DATA/nbp/HOFFMAN/nbp_1850-2010.nc``` |
| LORA |  http://dx.doi.org/10.25914/5b612e993d8ea   |   LORA monthly runoff estimates with associated uncertainties derived by optimally combining 11 state-of-the-art gridded runoff products from the eartH2Observe project  | ```DATA/mrro/LORA/LORA.nc``` |  http://creativecommons.org/licenses/by-nc-sa/4.0/ |
| MOD16A2 | https://doi.org/10.1016/j.rse.2011.02.019   |   MODIS (MOD16A2 level 4) global terrestrial evapotranspiration (ET) based on the Penman-Monteith (P-M) algorithm with MERRA meteorological forcings  | ```DATA/evspsbl/MOD16A2/et.nc``` |
| MODIS |    |  This product was derived from MODIS Climatology Leaf Area Index (LAI) from NCAR group. https://modis.gsfc.nasa.gov/data/  | ```DATA/lai/MODIS/lai_0.5x0.5.nc``` |
| NBCD2000 |    |   This product was derived from National Biomass and Carbon Dataset for the year 2000 originally in a raster format at 250m.  | ```DATA/biomass/NBCD2000/biomass_0.5x0.5.nc```     |
| NCSCDV22 |    |   This product was derived from Northern Circumpolar Soil Carbon Database V2.2 (NCSCDv22) in top 1m.  | ```DATA/cSoil/NCSCDV22/soilc_0.5x0.5.nc``` |
| NOAA.Emulated |    |  This product is generated from monthly NOAA GMD observations   |  ```DATA/co2/NOAA.GMD/co2.nc``` |
| NSIDC |    |     | ```DATA/permafrost/NSIDC/NSIDC_0.5x0.5.nc``` |
| Thurner |  https://onlinelibrary.wiley.com/doi/10.1111/geb.12125  |   Retrievals from synthetic aperture radar data using existing databases of wood density and allometric relationships between biomass compartments  | ```DATA/biomass/Thurner/biomass_0.5x0.5.nc``` |
| Tropical | https://www.pnas.org/doi/10.1073/pnas.1019576108   |  4079 in situ inventory plots, satellite light detection and ranging (LiDAR) samples of forest structure, and optical and microwave imagery (1-km resolution) to extrapolate estimates   | ```DATA/biomass/Tropical/biomass_0.5x0.5.nc```     |
| USForest |    |   This product was derived from Forest Biomass across the Lower 48 States and Alaska originally in a raster format at 250m.  | ```DATA/biomass/US.FOREST/biomass_0.5x0.5.nc``` |
| WECANN |    |     | ```DATA/gpp/WECANN/gpp.nc``` |
| WRMC.BSRN |    |     | ```DATA/rlds/WRMC.BSRN/rlds.nc``` |
