### ISSUE TITLE
Add IOMB-Data to the dev data project

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/ILAMB-workflow#15]
https://github.com/rubisco-sfa/IOMB-Data.git

**Comment by rbeucher** [comment]
Ilamb fetch can be used to add Ocean data

`ilamb-fetch --remote_root https://www.ilamb.org/IOMB-Data/`

**Comment by rhaegar325** [comment]
compare with their official config file for IOMB, we still need:
1.chl.nc
2.detoc.nc
3.dms.nc
4.dissic.nc
5.npp.nc
6.phyc.nc
7.zooc.nc
8.ws.nc
9.omlmax.nc
10. rsntds.nc
11.fgdms.nc
