### ISSUE TITLE
Review ILAMB Metadata-documentation for the Hive

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/ILAMB-workflow#18]
@svenbuder. @rhaegar325 has put together some documentation for ILAMB in that repo.

https://github.com/ACCESS-NRI/ILAMB-workflow/blob/main/ilamb_note.md

When you have time, it would be great to have a second opinion on the structure and content before we release it to the Hive.

**Comment by svenbuder** [comment]
On it.

**Comment by rbeucher** [comment]
Hi @svenbuder @rhaegar325, 

Do you have an update on this?

**Comment by svenbuder** [comment]
Hi @rbeucher @rhaegar325,

I had created a pull request for Rhaegar to check what he wants to include or neglect: https://github.com/ACCESS-NRI/ILAMB-workflow/pull/20

It might have gone under in the ocean of messages.

Cheers,


Sven

**Comment by rhaegar325** [comment]
HI, @svenbuder @rbeucher:
Really good job! I have just approve your pull request and merge it into main branch. Maybe I will make some change based on it but all on the right track.

**Comment by rbeucher** [comment]
OK my main comment is that most of the background setup is done by us and does not require much from the users.
The way the doc is organised should reflect that. 
It's good to have the details of how things are organised but that will largely be irrelevant for basic users.

**Comment by rhaegar325** [comment]
That's True, But we have a link `Run ilamb on NCI` at the beginning, maybe we could explain it so that user who only want to know how to run it on NCI can use this link to the content they want.

**Comment by rbeucher** [comment]
Yes I agree but maybe we want to re-organise the content so people don't feel like going ddown the rabbit hole.

**Comment by rhaegar325** [comment]
Sure, I will start working on it.
