### ISSUE TITLE
ilamb versions in conda environments

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-NRI/ILAMB-workflow#21]
The tutorial currently uses wrong environment and ilamb_dev module.
1) switch over to the xp65 environment (and tell users they need to be part of this project on NCI).
2) switch from ilamb_dev to access-med.
3) test the ilamb.__version__ to be >= 2.6
4) run both tutorial test and @rhaegar325 's tests after switching from ilamb_dev to access-med.

**Comment by rbeucher** [comment]
@rhaegar, we need to agree on a version of ILAMB and make sure it is available in xp65 AND hh5.

**Comment by rhaegar325** [comment]
OK, I think for now version 2.6 is work well in test environment `ilamb_dev` of xp65

**Comment by rbeucher** [comment]
There is no `ilamb_dev` environment anymore. You should test agains `access-med` in xp65 and `hh5`
