### ISSUE TITLE
`ilamb-tree-generator` in `hh5`

### ISSUE THREAD

**Issue by SeanBryan51** [ACCESS-NRI/ILAMB-workflow#30]
Can `ilamb-tree-generator` be added to the `hh5` conda environment? The tool is currently only available in the `access-med` conda environment in `xp65`. 

@rbeucher @rhaegar325

**Comment by rhaegar325** [comment]
Hi, @SeanBryan51, for `ilamb-tree-generator` we are still test on it and try to release a stable version, after that we will try to add it to `hh5`

**Comment by rbeucher** [comment]
@rhaegar325 can you deploy access-med-utils to hh5 when you have a chance?

**Comment by rbeucher** [comment]
@rhaegar325 have you done that?

**Comment by rhaegar325** [comment]
@rbeucher not yet, still waiting for reply from cws.nci, I will try to connect them again

**Comment by rbeucher** [comment]
@rhaegar325, do you have an update on this?

**Comment by rbeucher** [comment]
Considering that CLEX is ending at the end of the year. We recommend switching to xp65. ACCESS-MED environment
