### ISSUE TITLE
Bad netcdf file in replicated datasets

### ISSUE THREAD

**Issue by SeanBryan51** [ACCESS-NRI/ILAMB-workflow#31]
The dataset located in `/g/data/ct11/access-nri/replicas/ILAMB/albedo/CERESed4.1/albedo.nc` looks like it was produced incorrectly. Perhaps something to raise with the ILAMB folks?

When running a model-benchmark comparison for the albedo, ILAMB produces the following plot:

<img width="756" alt="benchmark-mean" src="https://github.com/ACCESS-NRI/ILAMB-workflow/assets/39685865/8c4feda2-9160-4a46-91df-9aae6e5f81da">

Inspecting the file directly with xarray:
```python
import matplotlib.pyplot as plt
import xarray
import numpy as np
benchmark_path = "/g/data/ct11/access-nri/replicas/ILAMB/albedo/CERESed4.1/albedo.nc"
ds = xarray.open_dataset(benchmark_path)
for t_index in np.arange(0, len(ds.albedo.time.values), 10)[1:4]:
    ds.albedo[t_index,:,:].plot()
    plt.show()
```

![download](https://github.com/ACCESS-NRI/ILAMB-workflow/assets/39685865/95ce1819-1007-45ab-a8e7-e382960ae000)

This issue might be better placed in the [ILAMB-Data](https://github.com/rubisco-sfa/ILAMB-Data) repo but I thought I'd run it by you guys first.

@rbeucher @rhaegar325

**Comment by rbeucher** [comment]
Hi @SeanBryan51,

Thanks for pointing this out. Let's make sure this has not been fixed already. @rhaegar325 can you try to download the latest file with ILAMB-data?

**Comment by rhaegar325** [comment]
OK, Working on it

**Comment by rhaegar325** [comment]
Hi, @rbeucher and @SeanBryan51 :
After I redownload the `ILAMB-DATA` and test on it, I found the data `DATA/albedo/CERESed4.1/albedo.nc` is indeed corrupted, I have reported this issue to `ILAMB-DATA` repo, let's see what they can do to fix it. Thanks @SeanBryan51 to report this issue.

**Comment by rbeucher** [comment]
@rhaegar325 Do we have an update on this? Has it been fixed?

**Comment by rhaegar325** [comment]
Yes, I found it's source data issue and I have already report it to ilamb-data group
